---
# tasks file for proxy-server-remove

- name: Stop Squid service
  ansible.builtin.service:
    name: squid
    state: stopped
    enabled: false

- name: Remove all files and service
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/init.d/squid
  - /etc/systemd/system/squid.service
  - /etc/squid
  - /var/spool/squid

- name: Remove Squid package
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
  - squid

- name: Clean dependencies
  ansible.builtin.apt:
    autoclean: yes

- name: Remove dependencies
  ansible.builtin.apt:
    autoremove: yes
    purge: yes

- name: Reload systemd services
  ansible.builtin.systemd:
    daemon_reexec: yes
